import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import axios from "axios";
import {
  BsSun,
  BsFillMoonStarsFill,
  BsFillBellFill,
  BsFillGridFill,
} from "react-icons/bs";
import dynamic from "next/dynamic";
import Layout from "@/components/layout";
import Axios from '@/helper/axios.helper'
import _ from 'lodash'
import { pages } from '@/utils/contanst'

export async function getServerSideProps({ req, res }) {
  const token = req.cookies["vechaitoken"];
  const { data: userData } = await Axios({
    url: "/api/customer/getbytoken",
    method: "GET",
    headers: { authorization: token },
  })

  return {
    props: {
      userData: userData[0]
    },
  };
}

export default function Dashboard({ userData }) {
  const { fullname, name, email, accessApp } = userData

  const [layoutPages, setLayoutPages] = useState([])

  const Map = dynamic(() => import("@/components/Map"), {
    ssr: false,
    loading: () => <p>Loading...</p>,
  });

  useEffect(() => {
    const accessAppsList = accessApp.split(', ')
    console.log(accessAppsList)
    if(accessAppsList && Array.isArray(accessAppsList)) {
      const userPages = _.filter(pages, (page) => {
        return accessAppsList.includes(page.key)
      })
      setLayoutPages(userPages)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="ico" href="/favicon.ico"></link>
      </Head>
      <main>
        <Layout pages={layoutPages} user={{ fullname, name, email }}>
          {/* <!-- ======Section======= --> */}
          <div className="heading" style={{ marginTop: 20 }}>
          <h2>Bản đồ vựa ve chai</h2>
          <Map></Map>
          </div>
          <div className="section flex flex-sb">
            {/* <!-- Section Left --> */}
            <div className="section-left">
              {/* <!-- ======Banner======= --> */}

              <div className="nfts">

                <div className="trending heading flex flex-sb">
                  <h2>Bài đăng ve chai cần bán</h2>
                  <p>Xem nhiều hơn</p>
                </div>

                {/* <!-- ======Categories======= --> */}

                <div className="categories flex flex-sb">
                  <div className="category flex">
                    <div className="icon">🔥</div>
                    <p>Trending</p>
                  </div>

                  <div className="category flex">
                    <div className="icon">🎨</div>
                    <p>Art</p>
                  </div>

                  <div className="category flex">
                    <div className="icon">🕹️</div>
                    <p>Game</p>
                  </div>

                  <div className="category flex">
                    <div className="icon">👗</div>
                    <p>Fashion</p>
                  </div>

                  <div className="category flex">
                    <div className="icon">🎵</div>
                    <p>Music</p>
                  </div>
                </div>

                {/* <!-- =====Browse NFT===== --> */}
                <div className="browse">
                  <div className="nft">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-1.jpg"
                      alt=""
                    />
                    <div className="title">Weary Artwork</div>
                    <div className="details flex flex-sb">
                      <div className="author flex">
                        <img
                          src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                          alt=""
                        />
                        <p>Hassnain Haider</p>
                      </div>
                      <div className="price">4.5 ETH</div>
                    </div>
                  </div>

                  <div className="nft">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-2.jpg"
                      alt=""
                    />
                    <div className="title">Spectrum of Color</div>
                    <div className="details flex flex-sb">
                      <div className="author flex">
                        <img
                          src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                          alt=""
                        />
                        <p>Hassnain Haider</p>
                      </div>
                      <div className="price">4 ETH</div>
                    </div>
                  </div>

                  <div className="nft">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-3.jpg"
                      alt=""
                    />
                    <div className="title">Vivid Artwork</div>
                    <div className="details flex flex-sb">
                      <div className="author flex">
                        <img
                          src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                          alt=""
                        />
                        <p>Hassnain Haider</p>
                      </div>
                      <div className="price">3.5 ETH</div>
                    </div>
                  </div>

                  <div className="nft">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-4.jpg"
                      alt=""
                    />
                    <div className="title">Natures Love</div>
                    <div className="details flex flex-sb">
                      <div className="author flex">
                        <img
                          src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                          alt=""
                        />
                        <p>Hassnain Haider</p>
                      </div>
                      <div className="price">5 ETH</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* <!-- Section Right --> */}
            <div className="section-right">

              <div className="top-creators">
                <div className="heading flex flex-sb">
                  <h2>Top thu mua</h2>
                  <p>Xem thêm</p>
                </div>

                <div className="creator flex flex-sb">
                  <div className="follow-creator flex">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                      alt=""
                    />
                    <div className="creator-details">
                      <h3>Hassnain Haider</h3>
                      <p>@hassnain</p>
                    </div>
                  </div>

                  <Link href="/" className="btn following">
                    Following
                  </Link>
                </div>

                <div className="creator flex flex-sb">
                  <div className="follow-creator flex">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                      alt=""
                    />
                    <div className="creator-details">
                      <h3>Hassnain Haider</h3>
                      <p>@hassnain</p>
                    </div>
                  </div>

                  <Link href="/" className="btn follow following">
                    Follow
                  </Link>
                </div>

                <div className="creator flex flex-sb">
                  <div className="follow-creator flex">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                      alt=""
                    />
                    <div className="creator-details">
                      <h3>Hassnain Haider</h3>
                      <p>@hassnain</p>
                    </div>
                  </div>

                  <Link href="/" className="btn follow following">
                    Follow
                  </Link>
                </div>

                <div className="creator flex flex-sb">
                  <div className="follow-creator flex">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                      alt=""
                    />
                    <div className="creator-details">
                      <h3>Hassnain Haider</h3>
                      <p>@hassnain</p>
                    </div>
                  </div>

                  <Link href="/" className="btn follow following">
                    Follow
                  </Link>
                </div>

                <div className="creator flex flex-sb">
                  <div className="follow-creator flex">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                      alt=""
                    />
                    <div className="creator-details">
                      <h3>Hassnain Haider</h3>
                      <p>@hassnain</p>
                    </div>
                  </div>

                  <Link href="/" className="btn follow following">
                    Follow
                  </Link>
                </div>

                <div className="creator flex flex-sb">
                  <div className="follow-creator flex">
                    <img
                      src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                      alt=""
                    />
                    <div className="creator-details">
                      <h3>Hassnain Haider</h3>
                      <p>@hassnain</p>
                    </div>
                  </div>

                  <Link href="/" className="btn follow following">
                    Follow
                  </Link>
                </div>
              </div>
            </div>
          </div>
          {/* <!-- ======End Section======= --> */}
        </Layout>
      </main>
    </>
  );
}