import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  const handle = () => {
    window.alert('test nè')
  }
  const router = useRouter()
  console.log(router.query)

  return (
    <>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://example.com/script.js"/>
      <main className={`${styles.main} ${inter.className}`}>

      </main>
    </>
  )
}
